# Site settings
title: Save Michigan Favorite Businesses
email: support@savemifaves.org
description: > # this means to ignore newlines until "baseurl:"
  Buy gift cards to help save local Michigan businesses and jobs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://:www.saveamiaves.org" # the base hostname & protocol for your site
twitter_username: saveamiaves
github_username:  saveamiaves

# Build settings
markdown: kramdown
