# Site settings
title: Save Michigan Favorite Businesses
copyright: Save MI Faves
email: support@savemifaves.org
description: > # this means to ignore newlines until "baseurl:"
  Buy gift cards to help save local Michigan businesses and jobs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://:www.saveamiaves.org" # the base hostname & protocol for your site
#google_groups: savemifaves
#meetup: Save-MI-Faves
twitter_username: saveMIfaves
github_username:  alfajango/savemifaves
google_analytics: "UA-161660791-1"

# Build settings
markdown: kramdown
