# Site settings
title: Save Ann Arbor Favorite Businesses
email: support@savea2faves.org
description: > # this means to ignore newlines until "baseurl:"
  Buy gift cards to help save local Ann Arbor businesses and jobs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://:ww.savea2faves.org" # the base hostname & protocol for your site
twitter_username: savea2faves
github_username:  savea2faves

# Build settings
markdown: kramdown
